---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
    - default: 
        cpu: 250m
      defaultRequest:
        cpu: 250m
      max: 
        cpu: "400m"
      min:
        cpu: 100m
      type: Container

---
apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
    - name: stress
      image: praveenbabu135/stress
      imagePullPolicy: Always
      command: ["sleep", "200"]